import type { Metadata } from "next";
import { LegalDocument, type LegalSection } from "@/components/legal/legal-document";
import { SITE } from "@/lib/constants";

export const metadata: Metadata = {
  title: `Terms of Service · ${SITE.name}`,
  description: "The terms that govern use of NEYA.",
};

const sections: LegalSection[] = [
  { title: "1. Acceptance of these terms", body: <p>These Terms of Service govern your use of NEYA, including neya.live and its event discovery, venue, booking, guestlist, ticket, and guide features. By creating an account, submitting content, making a purchase, or using the service, you agree to these terms and our Privacy Policy. If you do not agree, do not use NEYA.</p> },
  { title: "2. Eligibility and user accounts", body: <p>You must provide accurate information, keep your account credentials confidential, and promptly update information that changes. You are responsible for activity on your account. Some events, venues, or purchases may impose age restrictions or entry conditions; you are responsible for meeting them and for carrying any required identification. NEYA may refuse registration or require verification where reasonably necessary for security, fraud prevention, or compliance.</p> },
  { title: "3. Event information and submissions", body: <p>NEYA helps users discover events but does not guarantee that an event will occur, start on time, match its description, or remain available. Organisers and venues are responsible for the accuracy, legality, and timeliness of information they submit, including schedules, prices, images, capacity, age limits, accessibility information, and cancellation notices. You must have all rights and permissions needed to submit content. By submitting it, you grant NEYA a non-exclusive, worldwide, royalty-free licence to host, reproduce, adapt for formatting, display, and promote it in connection with operating and marketing the service.</p> },
  { title: "4. Venue submissions", body: <p>Venue listings must identify the submitting business or authorised representative and must not misrepresent ownership, affiliation, location, availability, or services. NEYA may review, edit for formatting, decline, suspend, or remove listings that are inaccurate, incomplete, unlawful, deceptive, or inconsistent with these terms. Approval of a listing is not an endorsement of the venue or a promise of placement, traffic, or sales.</p> },
  { title: "5. Tickets, guides, reservations, and payments", body: <><p>Where payment is offered through NEYA, Stripe processes the payment. Prices, taxes, fees, refund conditions, and availability shown at checkout control for that transaction. A completed payment does not override venue admission policies, lawful age restrictions, capacity limits, security checks, or organiser cancellation decisions.</p><p>Ticket purchasers and guide buyers must not resell, duplicate, alter, or misuse digital tickets, QR codes, or paid guide content. Reservation and guestlist requests are subject to venue approval, capacity, payment requirements, and the terms shown during booking. Unless a specific refund policy says otherwise, NEYA does not guarantee refunds for venue or organiser cancellations; support requests will be assessed based on the applicable transaction and available evidence.</p></> },
  { title: "6. Your responsibilities", body: <p>You must use NEYA lawfully, respectfully, and only for its intended purposes. You are responsible for your conduct at events and venues, for information you provide, and for obtaining any permissions needed for people, brands, music, or images in submitted content. NEYA is not responsible for disputes between users, venues, organisers, or third parties, although we may assist or take action where appropriate.</p> },
  { title: "7. Prohibited content and conduct", body: <ul className="list-disc space-y-2 pl-5"><li>Submitting false, misleading, infringing, defamatory, discriminatory, sexually exploitative, or unlawful content;</li><li>Impersonating a person or business, harvesting data, scraping the service, bypassing access controls, or interfering with the platform;</li><li>Using NEYA to send spam, manipulate listings, commit fraud, launder payments, or facilitate illegal activity;</li><li>Uploading malware, attempting unauthorised access, or exploiting a vulnerability without our written permission;</li><li>Reselling, sharing, or commercially exploiting tickets, QR codes, guides, or platform content except where expressly authorised.</li></ul> },
  { title: "8. Intellectual property", body: <p>NEYA and its logos, software, designs, text, and original content are owned by NEYA or its licensors and are protected by applicable intellectual-property laws. Except for the limited right to use the service under these terms, no rights are granted to you. Event and venue names, logos, photographs, and other third-party materials remain the property of their respective owners.</p> },
  { title: "9. Availability and limitation of liability", body: <p>NEYA is provided on an “as available” basis. To the maximum extent permitted by applicable law, we do not warrant uninterrupted availability, error-free operation, or the accuracy, safety, quality, legality, or suitability of third-party events, venues, organisers, content, or services. NEYA is not liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits, data, goodwill, travel costs, or missed events. Where liability cannot be excluded, NEYA&apos;s total liability for a claim related to the service will not exceed the amount you paid to NEYA for the transaction giving rise to that claim during the preceding twelve months.</p> },
  { title: "10. Suspension and termination", body: <p>You may stop using NEYA at any time. We may suspend or terminate access, remove content, cancel a transaction where permitted, or take other reasonable action if we believe you violated these terms, created risk for users or the service, engaged in fraud or unlawful conduct, or if required by law. Provisions that by their nature should survive termination, including intellectual-property, liability, and dispute provisions, will survive.</p> },
  { title: "11. Governing law and disputes", body: <p>These terms are governed by the laws of the Republic of Kosovo, without regard to conflict-of-law rules. Before starting formal proceedings, please contact us so we can try to resolve the issue informally. Subject to mandatory consumer-protection rules, courts with jurisdiction in Prishtina, Kosovo will have exclusive jurisdiction over disputes arising from these terms or the service.</p> },
  { title: "12. Changes and contact information", body: <p>We may update these terms to reflect changes to NEYA, our services, or legal requirements. The updated terms take effect when posted, unless a different effective date is stated. For questions, notices, or support, contact <a className="text-sky-300 hover:underline" href="mailto:neyakosova@gmail.com">neyakosova@gmail.com</a>.</p> },
];

export default function TermsPage() {
  return <LegalDocument title="Terms of Service" updated="28 July 2026" intro={<p>These Terms set out the agreement between you and NEYA when you use our service. Please read them carefully before creating an account, publishing a listing, booking a table, joining a guestlist, or making a purchase.</p>} sections={sections} />;
}
