"use client";

import { useCallback, useMemo, useState } from "react";
import Link from "next/link";
import { MapPin, Search } from "lucide-react";
import { AnimatedMap, type MapMarker } from "@/components/neya/animated-map";
import type { Event, Venue } from "@/types";
import { cn } from "@/lib/utils";

type Bounds = { west: number; south: number; east: number; north: number };
type Mode = "all" | "events" | "venues";
function inside(marker: MapMarker, bounds: Bounds) { return marker.lng >= bounds.west && marker.lng <= bounds.east && marker.lat >= bounds.south && marker.lat <= bounds.north; }
function distanceKm(a: { lat: number; lng: number }, b: { lat: number; lng: number }) { const r = 6371; const dLat = (b.lat - a.lat) * Math.PI / 180; const dLng = (b.lng - a.lng) * Math.PI / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(a.lat * Math.PI / 180) * Math.cos(b.lat * Math.PI / 180) * Math.sin(dLng / 2) ** 2; return r * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }

export function DiscoveryMap({ events, venues }: { events: Event[]; venues: Venue[] }) {
  const [mode, setMode] = useState<Mode>("all"); const [query, setQuery] = useState(""); const [bounds, setBounds] = useState<Bounds | null>(null); const [areaOnly, setAreaOnly] = useState(false); const [nearbyOnly, setNearbyOnly] = useState(false); const [location, setLocation] = useState<{ lat: number; lng: number } | null>(null); const [locationError, setLocationError] = useState<string | null>(null);
  const onBoundsChange = useCallback((next: Bounds) => setBounds(next), []);
  const markers = useMemo<MapMarker[]>(() => {
    const q = query.trim().toLowerCase(); const matches = (values: Array<string | undefined>) => !q || values.some((value) => value?.toLowerCase().includes(q));
    const eventMarkers = mode !== "venues" ? events.flatMap((event) => event.venue?.lat != null && event.venue.lng != null && matches([event.title, event.venue.name, event.genre, event.category, event.city_slug]) ? [{ lat: event.venue.lat, lng: event.venue.lng, slug: event.slug, title: event.title, kind: "event" as const, href: `/events/${event.slug}`, is_live: event.live_status }] : []) : [];
    const venueMarkers = mode !== "events" ? venues.flatMap((venue) => venue.lat != null && venue.lng != null && matches([venue.name, venue.category, venue.city_slug, ...(venue.music_genres ?? [])]) ? [{ lat: venue.lat, lng: venue.lng, slug: venue.slug, title: venue.name, kind: "venue" as const, href: `/venues/${venue.slug}`, is_live: venue.is_live }] : []) : [];
    const all = [...eventMarkers, ...venueMarkers]; const inArea = areaOnly && bounds ? all.filter((marker) => inside(marker, bounds)) : all; const nearby = nearbyOnly && location ? inArea.filter((marker) => distanceKm(location, marker) <= 15) : inArea; return location ? [...nearby].sort((a, b) => distanceKm(location, a) - distanceKm(location, b)) : nearby;
  }, [events, venues, mode, query, areaOnly, bounds, nearbyOnly, location]);
  function requestLocation() { if (!navigator.geolocation) { setLocationError("Location is not available in this browser."); return; } navigator.geolocation.getCurrentPosition((position) => { setLocation({ lat: position.coords.latitude, lng: position.coords.longitude }); setNearbyOnly(true); setLocationError(null); }, () => setLocationError("Location permission was not granted."), { enableHighAccuracy: false, maximumAge: 300000, timeout: 10000 }); }
  const center: [number, number] = markers[0] ? [markers[0].lng, markers[0].lat] : [21.1655, 42.6629];
  return <section className="mt-8"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3 sm:p-4"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-white/35" /><span className="sr-only">Search map</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search events, venues, genres, cities…" className="h-10 w-full rounded-xl border border-white/10 bg-black/40 pl-9 pr-3 text-sm text-white placeholder:text-white/35" /></label><button type="button" onClick={() => setAreaOnly((value) => !value)} disabled={!bounds} className={cn("h-10 rounded-xl border px-3 text-sm", areaOnly ? "border-sky-400/60 bg-sky-500/10 text-sky-100" : "border-white/15 text-white/70", !bounds && "cursor-not-allowed opacity-50")}>Search this area</button><button type="button" onClick={requestLocation} className={cn("h-10 rounded-xl border px-3 text-sm", nearbyOnly ? "border-sky-400/60 bg-sky-500/10 text-sky-100" : "border-white/15 text-white/70")}>{location ? "Nearby (15 km)" : "Find nearby"}</button></div><div className="mt-3 flex flex-wrap gap-2">{(["all", "events", "venues"] as Mode[]).map((value) => <button key={value} type="button" onClick={() => setMode(value)} className={cn("rounded-full border px-3 py-1.5 text-xs capitalize", mode === value ? "border-fuchsia-400/60 bg-fuchsia-500/15 text-fuchsia-100" : "border-white/15 text-white/65")}>{value}</button>)}</div>{locationError ? <p className="mt-2 text-xs text-amber-200">{locationError}</p> : null}</div><AnimatedMap className="mt-4" center={center} markers={markers} onBoundsChange={onBoundsChange} /><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{markers.slice(0, 18).map((marker) => <Link key={`${marker.kind}-${marker.slug}`} href={marker.href ?? "/events"} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-sm text-white/75 hover:border-sky-400/35"><MapPin className="h-4 w-4 text-sky-300" /><span className="truncate">{marker.title}</span>{location ? <span className="ml-auto text-xs text-white/40">{distanceKm(location, marker).toFixed(1)} km</span> : <span className="ml-auto text-xs capitalize text-white/40">{marker.kind}</span>}</Link>)}</div>{!markers.length ? <p className="mt-4 text-sm text-white/45">No mapped events or venues match these filters.</p> : null}</section>;
}
