#!/usr/bin/env python3
"""
Convert the official HyperFrames audio-reactive extraction output
(`extract-audio-data.py` -> raw JSON) into the `var AUDIO_DATA = {...};`
shape the audio-reactive reference documents, so the composition can load it
with a plain `<script src="audio-data.js"></script>`.

The value is normalized and reformatted only. No data is invented or resampled.

Usage:
    python build-audio-data.py audio-data.json audio-data.js
"""

import json
import sys

# Match the documented contract: frames[i].bands[] plus an overall amplitude.
# The extractor emits `bands`, `rms`, and `time`; keep all three and drop the
# redundant envelope metadata the runtime never reads.
KEEP_KEYS = ("time", "rms", "bands")


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    src, dst = sys.argv[1], sys.argv[2]

    with open(src, encoding="utf-8") as handle:
        raw = json.load(handle)

    frames = [{k: f[k] for k in KEEP_KEYS if k in f} for f in raw["frames"]]
    payload = {
        "fps": raw["fps"],
        "totalFrames": raw["totalFrames"],
        "bands": raw["bands"],
        "duration": raw["duration"],
        "frames": frames,
    }

    body = json.dumps(payload, separators=(",", ":"))

    with open(dst, "w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/build-audio-data.py - do not edit by hand.\n")
        handle.write("// Source: assets/music/neya-bed.mp3 via hyperframes-creative extract-audio-data.py\n")
        handle.write(f"var AUDIO_DATA = {body};\n")

    print(f"Wrote {dst} ({payload['totalFrames']} frames, {payload['bands']} bands)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
